#!/bin/bash

# Install Snap Applications
function install_snap_apps {
	NAME="Snap Applications"
	echo_message title "Starting installation of ${NAME,,}..."
	status="0"
	while [ "$status" -eq 0 ]; do
		# Draw window
		SNAPS=$(eval `resize` && whiptail \
			--notags \
			--title "Install $NAME" \
			--menu "\nWhat ${NAME,,} would you like to install?" \
			--ok-button "Install" \
			--cancel-button "Go Back" \
			$LINES $COLUMNS $(( $LINES - 12 )) \
			'install_snap_spotify'      'Spotify' \
			3>&1 1>&2 2>&3)

		case "${SNAPS}" in
			install_snap_spotify)
				# install Spotify
				install_snap_package "Spotify" "spotify" install_snap_apps
				;;
			*) 
				# cancel
				echo_message info "Returning..."
				status=1
				main
			;;
		esac
	done
}