#!/bin/bash

# Configure text editors by copying the 'editorconfig.in' file to ~/.editorconfig
function write_editorconfig {
	# Check list
	INPUT=$(dirname "$0")'/data/config/editorconfig.in'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Configure Text editors" \
		--yesno "Custom config file contains the following: \n\n$(while read LINE; do echo "  "$LINE; done < $INPUT) \n\nOverwrite existing config?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		echo_message info "Overwriting ~/.editorconfig..."
		# simply copy the list file to the aliases file
		cp $INPUT ~/.editorconfig
		echo_message success "Text editors successfully configured."
		whiptail --title "Finished" --msgbox "Text editors successfully configured." 8 56
		setup_dotfiles
	else
		setup_dotfiles
	fi
}

# Configure zsh by copying 'zshrc' file to ~/.zshrc
function write_zshconfig {
	# Check list
	INPUT=$(dirname "$0")'/data/config/.zshrc'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Configure Zsh" \
		--yesno "Custom config file contains the following: \n\n$(while read LINE; do echo "  "$LINE; done < $INPUT) \n\nOverwrite existing config?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		# setup oh-my-zsh
		sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
		echo_message info "Overwriting ~/.zshrc..."
		# simply copy the list file to the aliases file
		cp $INPUT ~/
		echo_message success "Zsh successfully configured."
		whiptail --title "Finished" --msgbox "Zsh successfully configured." 8 56
		setup_dotfiles
	else
		setup_dotfiles
	fi
}

# Configure vim by copying 'vimrc' file to ~/.vimrc and installing Vim Plug
function write_vimconfig {
	# Check list
	INPUT=$(dirname "$0")'/data/config/.vimrc'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Configure Vim" \
		--yesno "Custom config file contains the following: \n\n$(while read LINE; do echo "  "$LINE; done < $INPUT) \n\nOverwrite existing config?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		echo_message info "Installing Vim Plug..."
		# Install Vim Plug
		curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
		echo_message info "Overwriting ~/.vimrc..."
		# simply copy the file
		cp $INPUT ~/
		echo_message success "Vim successfully configured."
		whiptail --title "Finished" --msgbox "Vim successfully configured." 8 56
		setup_dotfiles
	else
		setup_dotfiles
	fi
}

# Install custom dotfiles
function setup_dotfiles {
	NAME="System Configuration"
	echo_message title "Starting ${NAME,,}..."
	# Draw window
	CONFIGURE=$(eval `resize` && whiptail \
		--notags \
		--title "$NAME" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'write_editorconfig'   'Set custom editor config' \
		'write_zshconfig'		   'Set zsh config' \
		'write_vimconfig'		   'Set vim config' \
		3>&1 1>&2 2>&3)
	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$CONFIGURE' function"
		$CONFIGURE
	else
		# Cancelled
		echo_message info "$NAME cancelled."
		main
	fi
}